---
# Make ceph user use sudo without password prompt

- name: Make ceph user use sudo without password
  template:
    src: sudoer.j2
    dest: "/etc/sudoers.d/10-{{ ceph_user }}"
    owner: root
    group: root
    mode: 0440
