---
# Setup EPEL & Ceph repository

- name: Install EPEL repository
  yum:
    name: "http://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  when: ansible_distribution_file_variety == 'RedHat'

- name: Setup Ceph repository
  template:
    src: ceph.repo.j2
    dest: /etc/yum.repos.d/ceph.repo
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_file_variety == 'RedHat'

- name: Setup Ceph repository
  command: "apt-add-repository \'deb https://download.ceph.com/debian-{{ ceph_release }}/ {{ ansible_lsb.codename }} main\'"
  when: ansible_distribution in ['Debian', 'Ubuntu']
