---
# Configure ceph-mon on every monitoring nodes

- name: Create default data directory for ceph-mon
  file:
    path: "/var/lib/ceph/mon/{{ ceph_cluster_name }}-{{ inventory_hostname }}"
    state: directory
    mode: 0755

- name: Populate the initial monitor daemon
  command: "ceph-mon --cluster {{ ceph_cluster_name }} --mkfs -i {{ inventory_hostname }} --monmap /tmp/monmap --keyring /tmp/{{ ceph_cluster_name }}.mon.keyring"

- name: Create done files for ceph-mon
  file:
    path: "/var/lib/ceph/mon/{{ ceph_cluster_name }}-{{ inventory_hostname }}/{{ item }}"
    state: touch
    mode: 0644
  with_items:
  - "done"
  - "systemd"

- name: Update owner & group permissions for files
  command: "chown {{ ceph_user }}:{{ ceph_group }} {{ item }}"
  with_items:
  - "-R /var/lib/ceph/mon"
  - "/etc/ceph/rbdmap"
  - "/etc/ceph/{{ ceph_cluster_name }}.conf"

- name: Edit default cluster name
  lineinfile:
    dest: /etc/sysconfig/ceph
    regexp: '^CLUSTER'
    line: 'CLUSTER={{ ceph_cluster_name }}'
    state: present
