---
# Configure passwordless SSH by root user

- name: Generate SSH key
  command: ssh-keygen -t rsa -N "" -f /root/.ssh/id_rsa
  args:
    creates:
    - "/root/.ssh/id_rsa"
    - "/root/.ssh/id_rsa.pub"
  ignore_errors: yes

- name: Get SSH public key
  command: cat /root/.ssh/id_rsa.pub
  register: ssh_pubkey

- name: Configure passwordless SSH
  authorized_key:
    user: root
    key: "{{ hostvars[item].ssh_pubkey.stdout }}"
  with_items: "{{ groups['all'] }}"

- name: Scan public key
  command: "ssh-keyscan -t rsa {{ short_name }},{{ ansible_host }}"
  register: ssh_keyscan

- name: Add to knonw_hosts file
  known_hosts:
    name: "{{ hostvars[item].short_name }}"
    path: /root/.ssh/known_hosts
    key: "{{ hostvars[item].ssh_keyscan.stdout }}"
    state: present
  with_items: "{{ groups['all'] }}"
