---
# Configure hostname

- name: Set hostname
  hostname:
    name: "{{ long_name }}"

- name: Set /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^{{ hostvars[item].ansible_host  }}'
    line: '{{ hostvars[item].ansible_host }}  {{ hostvars[item].short_name }}  {{ hostvars[item].long_name }}'
    state: present
  with_items: "{{ groups['all'] }}"
